---
# See: https://pre-commit.com/
exclude: |
  (?x)^(
    \.git/|
    \.git-crypt/.*|
    \.gitattributes|
    \.gitignore|
    .*/\.gitignore|
    .*/_todo/.*|
    .*-encrypted/.*|
    .*-encrypted\..*|
    .*/secrets/.*|
    \.editorconfig|
    .*/\.editorconfig|
    LICENSE|
    .*\.nu|
    .*/completions/_.*|
    flake\.lock|
    .*/Cargo\.lock|
    .*/uv\.lock|
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: detect-private-key
        fail_fast: true
      - id: check-added-large-files
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-xml
  - repo: local
    hooks:
      - id: shellharden
        name: shellharden
        entry: shellharden --replace
        language: system
        files: \.(sh|bash|envrc|envrc.*)$
      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        files: \.(sh|bash|envrc|envrc.*)$
      - id: shfmt
        name: shfmt
        entry: shfmt --indent 2 --simplify --write
        language: system
        files: \.(sh|bash|envrc|envrc.*)$
  - repo: local
    hooks:
      - id: nixfmt
        name: nixfmt
        entry: nixfmt
        language: system
        types: [nix]
      - id: just-fmt
        name: just format
        entry: bash -c 'just --fmt --unstable --justfile "$1"' --
        language: system
        files: (^|/)(\.)?justfile$
      - id: fish-indent
        name: fish_indent
        entry: fish_indent --write
        language: system
        types: [fish]
      - id: yamlfix
        name: yamlfix
        entry: yamlfix
        language: system
        types: [yaml]
      - id: taplo
        name: taplo format
        entry: taplo format
        language: system
        types: [toml]
      - id: biome
        name: biome format
        entry: biome format --write
        language: system
        files: \.(json|jsonc)$
      - id: markdownlint
        name: markdownlint-cli2
        entry: markdownlint-cli2 --fix
        language: system
        types: [markdown]
