---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-toml
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --
        language: system
        pass_filenames: true
        types: [rust]
      - id: nixfmt
        name: nixfmt
        entry: nixfmt --width=100 --
        language: system
        pass_filenames: true
        types: [nix]
      - id: markdownlint
        name: markdownlint-cli2
        entry: markdownlint-cli2 --fix
        language: system
        types: [markdown]
