---
env-traefik: ENC[AES256_GCM,data:/oMMm2wQy+vcEZCyctbjU988u5iJmcangu+Kdo8ugL+hV2/bbEUXkvcC+uMDsvxNQnx7vtf+Q1pamrT0/L2LshLf10FV2JzqbxyGR2aHtaU0xzE90SLU/9J2SkMZOYYkww==,iv:8hM2tuamNkYYCaAdSPYpIA2Hdns72TOB9Jb8xwixihg=,tag:dgUH89Xja0OBholwC5fXiA==,type:str]
sops:
  age:
    - recipient: age1yk5lf2dm7smps9kysmasrnu9qcefk7spdgaah3h2yuprgs225vgqlr33pv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZzJUY0tnTDBOcGp5RndI
        cEgzblRRTklBQlh2b0xhT1Nwdlg3OEl1eFRNCjNhM0p1QzdHaDhCWFc5eVB4VHAw
        Sm94V29DbVVhT1RkamtucVJLenF0UU0KLS0tIFc0S2VGUnlTU294bGhjY1BsZDAx
        cHJKVVhvR0lEaml4NUJkMkppYTZ3aDgKqhxSxQ74jyaN6qRKR+72dq5IVuczvTSs
        LS8+iqsZDo3rcokn6pCVBKrhaOSCV3F8xkVopbj6pJLsMIsddN36CA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2025-06-14T14:22:52Z'
  mac: ENC[AES256_GCM,data:JdpYIs9/o6cuW8C9/mPIiIN15YwKUEkJS90amYDhyLcu70vZC1xGV5KDbG+GU4yneCnN61EPF+Wkwh6v4OSxx8a+qFGWlF433xd08zmBY7/8f163u1Dbx0EykXhx3b4Tjr2xkrU6Kz+uJ1oP1I5rNb69kDQnZbY9e2QnsfxgAy4=,iv:CUzu5m27aTBpI+bVuOelgauryciXlOsfsY11qTL75Lg=,tag:CeaokH0GKGDzZWKMaSUo8Q==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
